# Generated by Django 4.2.1 on 2023-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SL.NO', models.CharField(max_length=100)),
                ('Sub Assy part No', models.CharField(max_length=100)),
                ('REV NO', models.CharField(max_length=100)),
                ('Child Part No', models.CharField(max_length=100)),
                ('Part_Name', models.CharField(max_length=100)),
                ('Quantity', models.FloatField()),
                ('Surface Finish', models.CharField(max_length=100)),
                ('Material', models.CharField(max_length=100)),
                ('Qty In Drawing', models.CharField(max_length=100)),
                ('Thickness', models.FloatField()),
                ('Width', models.FloatField()),
                ('Length', models.FloatField()),
                ('Blank Wt', models.FloatField()),
                ('Powder Coating Area', models.FloatField()),
                ('Powder Usage in Kgs', models.FloatField()),
                ('Assembly/Sub part', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=100)),
                ('Source', models.CharField(max_length=100)),
                ('Wire Rack/Non Wire Rack Parts', models.CharField(max_length=100)),
                ('Revion No', models.CharField(max_length=100)),
                ('Revision Details', models.CharField(max_length=100)),
                ('Tapping', models.CharField(max_length=100)),
                ('No. Of Bends', models.FloatField()),
                ('Clinching /Riveting', models.CharField(max_length=100)),
                ('Welding', models.CharField(max_length=100)),
                ('METAL STAMP ', models.CharField(max_length=100)),
                ('POWDER COATING', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('planner_name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('batch_control', models.IntegerField()),
                ('product_number', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('machines_available', models.IntegerField()),
            ],
        ),
    ]
