# Generated by Django 4.2.1 on 2023-06-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomviewer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
