# Generated by Django 4.2.2 on 2023-06-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomviewer', '0003_alter_bomdetail_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BomDetail',
        ),
    ]
