# Generated by Django 4.2.2 on 2023-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=80)),
                ('Emp_Id', models.CharField(max_length=100, unique=True)),
                ('Emp_Role', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
