# Generated by Django 4.2.1 on 2023-06-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('orderNumber', models.IntegerField()),
                ('productNumber', models.IntegerField()),
                ('productName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('orderPlacedDate', models.DateField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
