# Generated by Django 4.2.2 on 2023-06-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cust_AssetList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerasset',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customerasset',
            name='city',
        ),
    ]
