# Generated by Django 4.2.1 on 2023-06-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_code', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('machine_type', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('purchased_date', models.DateField()),
                ('last_maintenance_date', models.DateField()),
                ('next_maintenance_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('factory_location', models.CharField(max_length=100)),
                ('machine_layout', models.CharField(max_length=100)),
            ],
        ),
    ]
