# Generated by Django 4.2.1 on 2023-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mach', '0004_rename_capacity_machine_asset_capacityvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_asset',
            name='machineCode',
            field=models.CharField(max_length=100),
        ),
    ]
